language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools # important to always do this first, since the version installed of platform-tools below depends on it
    - platform-tools
    - build-tools-24.0.0
    - android-24

env:
  global:
  - TERM=dumb
